### ISSUE TITLE
编译不了，能不能把需要的文件都打包上来

### ISSUE THREAD

**Issue by icyfox168168** [ruitard/PaddleOCR-deployA#1]

**Comment by ruitard** [comment]
抱歉，项目还在开发中，有一些地方还不完善。

那些模型库文件体积较大，不应该作为项目的一部分上传到 Git 仓库，还是单独下载吧。

更新了 README 文档，详细补充了一下编译细节

**Comment by icyfox168168** [comment]
好的，等下试试，希望继续更新
